Repository DUNE-DAQ/hdf5libs, pull requests merged in 2024-03, with the labels that each got.

#75 Updated the file layout version number, and added support for it in hdf5_dump.py
  include/hdf5libs/HDF5FileLayout.hpp
  scripts/hdf5_dump.py
Labels: deliverable subtask

#74 Added Detailed HSI Fragment Outputs
  test/apps/HDF5LIBS_TestDumpRecord.cpp
Labels: enhancement, miscellaneous deliverable

#76 Updated hdf5_dump.py to take into account new larger size for trigger_type
  scripts/hdf5_dump.py
Labels: miscellaneous deliverable
